export const data = [
    {
        id: 1,
        name: "Party dress",
        searchTerm: ["woman","dress"],
        title: "party-dress",
        about: "Feminine and minimalistic, elegant and comfortable, sexy but not vulgar - that’s what we can say about this dress. It creates the ideal line of a woman's silhouette, attracting the eye, but not allowing more to be seen.",
        sizeOne: "S 36",
        sizeTwo: "M 38",
        sizeFree: "L 40",
        sizeFour: "XL 42",
        price: 300.99,
        image: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8ZHJlc3N8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60"
    },
    {
        id: 2,
        name: "Summer dress",
        searchTerm: ["woman","dress"],
        title: "summer-dress",
        about: "A summer red dress is a stylish and easy choice for hot days. Made from breathable fabric, it provides comfort even in the warmest weather. Ideal for walks, parties or romantic meetings.",
        sizeOne: "S 36",
        sizeTwo: "M 38",
        sizeFree: "L 40",
        sizeFour: "XL 42",
        price: 204.99,
        image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8ZHJlc3N8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60"
    },
    {
        id: 3,
        name: "Fancy pants",
        searchTerm: ["woman", "pants"],
        title: "fancy-pants",
        about: "Unusual pale pink trousers are a bright accent in your wardrobe. An elegant cut with interesting details emphasizes individuality and style. Lightweight and pleasant to the touch fabric provides comfort throughout the day. Suitable for both everyday looks and special occasions.",
        sizeOne: "S 36",
        sizeTwo: "M 38",
        sizeFree: "L 40",
        sizeFour: "XL 42",
        price: 199.99,
        image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8cGFudHN8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60"
    },
    {
        id: 4,
        name: "Jeans",
        searchTerm: ["woman", "pants"],
        title: "jeans-woman",
        about: "Women's denim skinnies are the perfect combination of style and comfort. Soft and stretchy denim perfectly accentuates your figure while allowing freedom of movement. The classic design is suitable for any look - from everyday to evening. A versatile choice for your wardrobe!",
        sizeOne: "S 36",
        sizeTwo: "M 38",
        sizeFree: "L 40",
        sizeFour: "XL 42",
        price: 100.99,
        image: "https://images.unsplash.com/photo-1584370848010-d7fe6bc767ec?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8dHJvdXNlcnN8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60"
    },
    {
        id: 5,
        name: "Cute skirt",
        searchTerm: ["woman", "skirt"],
        title: "cute-skirt",
        about: "A cute soft pink midi skirt is the embodiment of lightness and romance. Made from airy fabric that flows beautifully as you move. The comfortable fit and sleek design make it ideal for summer walks, meetings or special occasions. An excellent choice for creating a feminine look!",
        sizeOne: "S 36",
        sizeTwo: "M 38",
        sizeFree: "L 40",
        sizeFour: "XL 42",
        price: 320.99,
        image: "https://images.unsplash.com/photo-1592301933927-35b597393c0a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjF8fHNraXJ0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60"
    },
    {
        id: 6,
        name: "Beauty",
        searchTerm: ["woman", "skirt"],
        title: "beauty",
        about: "A light, long, loose-fitting summer skirt in sunny yellow is the perfect choice for warm days. Airy fabric keeps you comfortable and cool, while the loose silhouette gives you freedom of movement. This skirt will become a bright accent in your summer wardrobe, suitable for both walking and relaxing by the sea.",
        sizeOne: "S 36",
        sizeTwo: "M 38",
        sizeFree: "L 40",
        sizeFour: "XL 42",
        price: 278.99,
        image: "https://images.unsplash.com/photo-1594226801341-41427b4e5c22?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fHNraXJ0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60"
    },
    {
        id: 7,
        name: "Business meeting",
        searchTerm: ["woman", "shirt"],
        title: "business-meeting",
        about: "A business white blouse is an elegant choice for the office and meetings. The sleek design with a sophisticated cut emphasizes femininity and adds sophistication to the look. Soft and pleasant fabric provides comfort throughout the day. Pairs perfectly with skirts, trousers and business suits.",
        sizeOne: "S 36",
        sizeTwo: "M 38",
        sizeFree: "L 40",
        sizeFour: "XL 42",
        price: 255.99,
        image: "https://images.unsplash.com/photo-1608234807905-4466023792f5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mzl8fHNoaXJ0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60"
    },
    {
        id: 8,
        name: "Lunch with friends",
        searchTerm: ["woman", "shirt"],
        title: "lunch-with-friends",
        about: "A white shirt with blue stripes is a stylish and versatile wardrobe item. The classic cut with neat collar and cuffs creates an elegant look, while contrasting stripes add freshness and dynamism. Suitable for the office, casual outings and informal meetings. Easily combined with jeans, trousers or skirts.",
        sizeOne: "S 36",
        sizeTwo: "M 38",
        sizeFree: "L 40",
        sizeFour: "XL 42",
        price: 234,
        image: "https://images.unsplash.com/photo-1605881528191-68f38c78e3d3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTkxfHxzaGlydHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60"
    },
    {
        id: 9,
        name: "Carrie shoes",
        searchTerm: ["woman", "shoes"],
        title: "carrie-shoes",
        about: "Pink and purple patent leather stilettos are a bright accent for a bold and elegant look in the style of Carrie Bradshaw. The glossy finish emphasizes the richness of the color, and the elegant stiletto heel visually lengthens the legs, adding grace. Ideal for evening outings, celebrations or a spectacular finish to a stylish outfit.",
        sizeOne: 36,
        sizeTwo: 37,
        sizeFree: 38,
        sizeFour: 39,
        price: 305.99,
        image: "https://images.unsplash.com/photo-1573100925118-870b8efc799d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8aGVlbHN8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60"
    },
    {
        id: 10,
        name: "Amanda shoes",
        searchTerm: ["woman", "shoes"],
        title: "amanda-shoes",
        about: "Black shoes with thin long stiletto heels with red soles are a classic that combines elegance and audacity. The sophisticated design with a distinctive accent on the sole conveys sophisticated taste and confidence. An ideal choice for evening outings, business events or creating a stylish look with character.",
        sizeOne: 36,
        sizeTwo: 37,
        sizeFree: 38,
        sizeFour: 39,
        price: 275.99,
        image: "https://images.unsplash.com/photo-1627631457335-d1041fd0cb8c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fGhlZWxzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60"
    },
    {
        id: 11,
        name: "Miranda shoes",
        searchTerm: ["woman", "shoes"],
        title: "miranda-shoes",
        about: "Stiletto sandals with a graceful edge at the front are a sophisticated and striking choice for special occasions. Light decor adds playfulness and luxury, and a thin heel emphasizes the elegance of the look. These sandals are ideal for evening wear, cocktail dresses or romantic dates.",
        sizeOne: 36,
        sizeTwo: 37,
        sizeFree: 38,
        sizeFour: 39,
        price: 205.99,
        image: "https://images.unsplash.com/photo-1554238113-6d3dbed5cf55?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mzl8fGhlZWxzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60"
    },
    {
        id: 12,
        name: "Cute dress",
        searchTerm: ["woman", "dress"],
        title: "cute-dress",
        about: "A bright silver minidress with one bare arm is a bold and expressive choice for an evening look. The shimmering fabric accentuates every curve, while the asymmetrical off-the-shoulder design adds sexiness and edge. Ideal for late night parties, club outings or stylish events.",
        sizeOne: "S 36",
        sizeTwo: "M 38",
        sizeFree: "L 40",
        sizeFour: "XL 42",
        price: 355.99,
        image: "https://images.unsplash.com/photo-1582533561751-ef6f6ab93a2e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8c2tpcnR8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60"
    },
    {
        id: 13,
        name: "Pants",
        searchTerm: ["woman", "pants"],
        title: "pants",
        about: "Unusual yellow pants with asymmetrical prints are a bright and original addition to your wardrobe. Experimental patterns create dynamism and attract attention, while bright yellow adds energy and mood. These pants are perfect for bold looks.",
        sizeOne: "S 36",
        sizeTwo: "M 38",
        sizeFree: "L 40",
        sizeFour: "XL 42",
        price: 100.99,
        image: "https://images.unsplash.com/photo-1517438476312-10d79c077509?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NzN8fHBhbnRzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=800&q=60"
    },
    {
        id: 14,
        name: "Lunch with friends",
        searchTerm: ["woman", "skirt"],
        title: "friends-lunch",
        about: "A black loose-fitting skirt is a classic and versatile wardrobe item. Light and airy, it gives comfort and freedom of movement. The elegant design without unnecessary details makes it ideal for creating both casual and more elegant looks. Suitable for combination with blouses, T-shirts, tops and jackets.",
        sizeOne: "S 36",
        sizeTwo: "M 38",
        sizeFree: "L 40",
        sizeFour: "XL 42",
        price: 274,
        image: "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8c2tpcnR8ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60"
    },
    {
        id: 15,
        name: "Lunch with friends",
        searchTerm: ["woman", "shirt"],
        title: "lunch-with-friends",
        about: "A white shirt with blue stripes is a stylish and versatile wardrobe item. The classic fit with neat collar and cuffs adds elegance, while alternating stripes create a dynamic and modern look. Great for office outfits, casual looks or more relaxed get-togethers. Easily combined with jeans, trousers or skirts.",
        sizeOne: "S 36",
        sizeTwo: "M 38",
        sizeFree: "L 40",
        sizeFour: "XL 42",
        price: 284.99,
        image: "https://images.unsplash.com/photo-1559334417-a57bd929f003?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjIzfHxzaGlydHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60"
    },
    {
        id: 16, 
        name: "Men's business trousers",
        searchTerm: ["man", "pants"],
        title: "mens-business-trousers",
        about: "Men's tapered trousers are a stylish and modern choice for any occasion. The tapering silhouette emphasizes the figure and creates an elegant look. Made from quality materials, these trousers provide comfort and freedom of movement, suitable for both business meetings and casual outings. Pairs perfectly with shirts, jackets and casual outfits.",
        sizeOne: "M 32",
        sizeTwo: "L 34",
        sizeFree: "XL 36",
        sizeFour: "XXL 38",
        price: 175.00,
        image: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
        id: 17,
        name: "Men's street pants",
        searchTerm: ["man", "pants"],
        title: "street-pants",
        about: "Men's black jeans are a classic that never goes out of style. Made from durable and stretchy denim, they provide comfort and a perfect fit. The black color gives them versatility, making them easy to pair with any tops, shirts or sweaters. An excellent choice for creating stylish and discreet looks, suitable for both work and everyday occasions.",
        sizeOne: "M 32",
        sizeTwo: "L 34",
        sizeFree: "XL 36",
        sizeFour: "XXL 38",
        price: 152.00,
        image: "https://images.unsplash.com/photo-1514311548104-ae305aac4688?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDJ8fHxlbnwwfHx8fHw%3D"
    },
    {
        id: 18,
        name: "Men's jeans",
        searchTerm: ["man", "pants"],
        title: "mens-jeans",
        about: "Men's dark distressed jeans are a stylish and slightly daring wardrobe item. The distressed effect gives them uniqueness and character, creating an informal and slightly rocker look. These jeans are ideal for everyday outings and can be easily combined with T-shirts, shirts or jumpers, adding a relaxed and individual touch to each look.",
        sizeOne: "M 32",
        sizeTwo: "L 34",
        sizeFree: "XL 36",
        sizeFour: "XXL 38",
        price: 205.00,
        image: "https://images.unsplash.com/photo-1511196044526-5cb3bcb7071b?q=80&w=1364&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
        id: 19,
        name: "Men's denim jacket",
        searchTerm: ["man", "jacket"],
        title: "denim-jacket",
        about: "A men's light denim jacket is an excellent choice for creating a stylish and relaxed look. Lightweight and comfortable, it combines the classic elements of a blazer with the relaxed feel of denim. This jacket is ideal for casual outings, meetings with friends or more relaxed business events. Easily pairs with trousers, jeans and t-shirts to create layered and fashionable looks.",
        sizeOne: "M 32",
        sizeTwo: "L 34",
        sizeFree: "XL 36",
        sizeFour: "XXL 38",
        price: 252.00,
        image: "https://images.unsplash.com/photo-1516257984-b1b4d707412e?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
        id: 20,
        name: "Men's shirt",
        searchTerm: ["man", "shirt"],
        title: "mens-shirt",
        about: "A men's blue shirt is a versatile and stylish wardrobe item. The lightweight, soft-touch fabric is perfect for warmer days, while the classic cut with neat collar and cuffs adds an elegant touch. The blue color adds freshness and brightness, making this shirt suitable for both office outfits and casual or evening looks. Pairs perfectly with trousers, jeans and jackets.",
        sizeOne: "M 32",
        sizeTwo: "L 34",
        sizeFree: "XL 36",
        sizeFour: "XXL 38",
        price: 95.00,
        image: "https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE1fHx8ZW58MHx8fHx8"
    },
    {
        id: 21,
        name: "Men's pullover",
        searchTerm: ["man", "pullover"],
        title: "pullover",
        about: "A men's black pullover is a classic and versatile wardrobe item. Made from soft and warm fabric, it's perfect for cold days, keeping you cozy and comfortable. The simple yet stylish design pairs easily with jeans, trousers or shorts, adding elegance and sophistication to your look. Great for both casual and more formal outfits.",
        sizeOne: "M 32",
        sizeTwo: "L 34",
        sizeFree: "XL 36",
        sizeFour: "XXL 38",
        price: 215.00,
        image: "https://images.unsplash.com/photo-1635205383144-402b892efa23?q=80&w=1365&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
        id: 22,
        name: "Baby dress",
        searchTerm: ["baby", "dress"],
        title: "baby-dress",
        about: "A peach dress for a girl is a delicate and charming product, ideal for special occasions. The lightweight fabric and airy fit create comfort and freedom of movement, while the peach hue adds warmth and brightness to the look. Suitable for holidays, photo shoots or family celebrations.",
        sizeOne: "98-104",
        sizeTwo: "104-110",
        sizeFree: "110-116",
        sizeFour: "116-120",
        price: 78.00,
        image: "https://images.pexels.com/photos/5693890/pexels-photo-5693890.jpeg?auto=compress&cs=tinysrgb&w=600"
    },
    {
        id: 23,
        name: "Girls stylish dress",
        searchTerm: ["baby", "dress"],
        title: "stylish-dress",
        about: "A children's warm dress is an ideal choice for special events in the cold season. Made from soft and warm fabric, it will provide comfort and protection from the cold, while maintaining elegance and style. The classic style with neat details makes the dress suitable for holidays, weddings or other special events. It will highlight youthful grace and create an unforgettable image for your little fashionista.",
        sizeOne: "98-104",
        sizeTwo: "104-110",
        sizeFree: "110-116",
        sizeFour: "116-120",
        price: 122.00,
        image: "https://images.pexels.com/photos/30181050/pexels-photo-30181050.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
    },
    {
        id: 24,
        name: "Teddy bear",
        searchTerm: ["baby", "toys"],
        title: "teddy-bear",
        about: "A large teddy bear is a soft and cozy friend that will be an ideal gift for any age. With a soft and fluffy coating, it gives warmth and comfort, creating a cozy atmosphere in the home. This bear is ideal for cuddling and will become a real companion for small children, as well as an original decoration for the bedroom or living room. Its size and cute appearance make it a special gift for any occasion.",
        sizeOne: "20 in",
        sizeTwo: "30 in",
        sizeFree: "40 in",
        sizeFour: "50 in",
        price: 77.00,
        image: "https://images.pexels.com/photos/12114817/pexels-photo-12114817.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
    },
    {
        id: 25,
        name: "Plush sheep",
        searchTerm: ["baby", "toys"],
        title: "plush-sheep",
        about: "A plush sheep is a soft and sweet friend that will bring comfort and warmth to any home. With soft-to-touch fur and kind eyes, she will become a favorite companion for children and adults. This baby toy is perfect for cuddling and will also make an adorable decorative addition to a child's room or a gift for loved ones. A gentle and cozy appearance will create an atmosphere of comfort and care.",
        sizeOne: "10 in",
        sizeTwo: "15 in",
        sizeFree: "20 in",
        sizeFour: "25 in",
        price: 49.00,
        image: "https://images.pexels.com/photos/4887086/pexels-photo-4887086.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
    },
    {
        id: 26,
        name: "Teddy bunny",
        searchTerm: ["baby", "toys"],
        title: "teddy-bunny",
        about: "A cute toy bunny is a charming and soft friend who gives joy and comfort. With long ears and kind eyes, this little bunny will become a favorite companion for children and is ideal for cuddling. Perfect as a gift or decor for a children's room, adding warmth and tenderness to the atmosphere. A toy that will delight and bring smiles every day.",
        sizeOne: "10 in",
        sizeTwo: "15 in",
        sizeFree: "20 in",
        sizeFour: "25 in",
        price: 53.00,
        image: "https://images.pexels.com/photos/19314757/pexels-photo-19314757.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
    },
    {
        id: 27,
        name: "Children's educational cubes",
        searchTerm: ["baby", "toys"],
        title: "educational-cubes",
        about: "Large educational cubes for children are a fascinating and useful toy that promotes the development of motor skills, logic and imagination. Bright and safe, they are ideal for little ones, helping develop counting skills, color vision and motor coordination. These toys make great gifts that will delight your child and promote learning through play.",
        sizeOne: "10 in",
        sizeTwo: "20 in",
        sizeFree: "25 in",
        sizeFour: "35 in",
        price: 43.00,
        image: "https://images.pexels.com/photos/298825/pexels-photo-298825.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
    }
]  