export const datasale = [
    {
        id: 1,
        name: "Autumn sweater",
        searchTerm: "sweater",
        title: "autumn-sweater",
        about: "Add a touch of tenderness and coziness to your wardrobe with this soft purple women's sweater. Made from soft, comfortable material, it's perfect for cooler days. The sweater has a relaxed fit that provides comfort and style, and the versatile shade easily pairs with jeans, skirts or trousers.  Made from high quality knitted fabric. It has a minimalistic design, with a round neckline and neat trim. Also, the delicate lavender color adds femininity to the look and is suitable for everyday wear and cozy weekends.",
        sizeOneSale: "S 36",
        sizeTwoSale: "M 38",
        sizeFreeSale: "L 40",
        sizeFourSale: "XL 42",
        price: "40.99",
        image: "https://images.unsplash.com/photo-1589697547048-962940abc062?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
        id: 2,
        name: "Flower sweater",
        searchTerm: "sweater",
        title: "flower-sweater",
        about: "A bright, stylish and cozy multi-colored sweater will become a real highlight of your wardrobe! Its unique design with a harmonious combination of colors will lift your spirits even on the cloudiest days. Made from soft and warm material, it will provide comfort and freedom of movement, ideal for walks, meetings with friends or cozy evenings at home. Let yourself stand out and add a pop of color to your everyday style!",
        sizeOneSale: "S 36",
        sizeTwoSale: "M 38",
        sizeFreeSale: "L 40",
        sizeFourSale: "XL 42",
        price: "32.99",
        image: "https://images.unsplash.com/photo-1677848103508-e443dfedf8d2?q=80&w=1370&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
        id: 3,
        name: "Style sweater",
        searchTerm: "sweater",
        title: "style-sweater",
        about: "A stylish black and white patterned sweater is the epitome of elegance and comfort. Its classic color combination and original patterns create a harmonious look that is suitable for any occasion. Made from high-quality material, it will give warmth and comfort on cool days, while remaining a fashionable accent to your wardrobe. Add a touch of sophistication to your look with this sweater and it will become your favorite item for the cold season!",
        sizeOneSale: "S 36",
        sizeTwoSale: "M 38",
        sizeFreeSale: "L 40",
        sizeFourSale: "XL 42",
        price: "52.90",
        image: "https://images.unsplash.com/photo-1641420889725-12098ed75371?q=80&w=1364&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
        id: 4,
        name: "Nike shoes",
        searchTerm: "shoes",
        title: "nike-shoes",
        about: "Stylish white Nike sneakers are the perfect choice for those who value comfort and minimalist design. These sneakers are designed to provide all-day comfort while remaining a versatile everyday staple. The sleek white color and signature Nike details will highlight your personality and sense of style. Upper material: Hard-wearing and breathable leather for comfort and durability. Outsole: Lightweight and shock-absorbing, designed for reliable traction. Step into style and confidence with these white Nike sneakers that will easily fit into any wardrobe!",
        sizeOneSale: "S 36",
        sizeTwoSale: "M 38",
        sizeFreeSale: "L 40",
        sizeFourSale: "XL 42",
        price: "42.00",
        image: "https://images.unsplash.com/photo-1512374382149-233c42b6a83b?q=80&w=1335&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
        id: 5,
        name: "Boots",
        searchTerm: "shoes",
        title: "boots",
        about: "Women's brown boots are a combination of style, reliability and functionality. These shoes are created for active and courageous girls who value comfort and confidence at every step. The deep brown color adds versatility, while quality materials and thoughtful design ensure comfort even over long periods of wear. Material: genuine leather, resistant to wear and external influences. Outsole: Textured for maximum traction on all surfaces. These brown boots will be your reliable companion in any weather and will add style to your look.",
        sizeOneSale: "S 36",
        sizeTwoSale: "M 38",
        sizeFreeSale: "L 40",
        sizeFourSale: "XL 42",
        price: "53.00",
        image: "https://images.unsplash.com/photo-1542841791-1925b02a2bbb?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
        id: 6,
        name: "Black dress",
        searchTerm: "dress",
        title: "black-dress",
        about: "A summer black long dress with two expressive cutouts on the sides is the epitome of elegance and boldness. This stylish outfit perfectly emphasizes your figure, adding a touch of mystery and charm. Lightweight fabric ensures comfort even in hot weather, and the versatile black color makes the dress an ideal choice for walks, parties or romantic meetings. Make your summer unforgettable with this black long dress that will give you confidence and highlight your personality!",
        sizeOneSale: "S 36",
        sizeTwoSale: "M 38",
        sizeFreeSale: "L 40",
        sizeFourSale: "XL 42",
        price: "24.00",
        image: "https://images.unsplash.com/photo-1524504259109-ddd837233694?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
        id: 7,
        name: "Pink dress",
        searchTerm: "dress",
        title: "pink-dress",
        about: "This elegant pink mini dress with strappy bodycon is the perfect choice for a bold and feminine look. Its soft pink hue emphasizes freshness and tenderness, and its tight cut accentuates the figure. This dress is the perfect outfit for parties, dates or outings in warm weather. Show off your flamboyance and confidence with this pink mini dress—a style that's sure to turn heads!",
        sizeOneSale: "S 36",
        sizeTwoSale: "M 38",
        sizeFreeSale: "L 40",
        sizeFourSale: "XL 42",
        price: "37.00",
        image: "https://images.unsplash.com/photo-1609533896512-68e72be46a33?q=80&w=1312&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
        id: 8,
        name: "Red dress",
        searchTerm: "dress",
        title: "red-dress",
        about: "An airy long red dress is the embodiment of passion and sophistication. Its lightweight, flowing fabric creates a dramatic silhouette, perfect for special occasions, romantic evenings or sunset walks. The bright red color emphasizes femininity and confidence, attracting admiring glances. Be the star of any event with this sophisticated red dress that gives you a feeling of lightness and grace!",
        sizeOneSale: "S 36",
        sizeTwoSale: "M 38",
        sizeFreeSale: "L 40",
        sizeFourSale: "XL 42",
        price: "45.00",
        image: "https://images.unsplash.com/photo-1508742345712-0656a285ac27?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
        id: 9,
        name: "Green dress",
        searchTerm: "dress",
        title: "green-dress",
        about: "A summer green long shirt dress with large patterns is a stylish and comfortable solution for warm days. A bright green shade refreshes the look, and spectacular large patterns add originality. The shirtdress's versatile style combines comfort and functionality, ideal for both outings and everyday activities. Feel the lightness and freshness of summer with this green shirt dress - it will perfectly highlight your personality and style!",
        sizeOneSale: "S 36",
        sizeTwoSale: "M 38",
        sizeFreeSale: "L 40",
        sizeFourSale: "XL 42",
        price: "36.00",
        image: "https://images.unsplash.com/photo-1725602260136-3bc7d89d174e?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
        id: 10,
        name: "Not today",
        searchTerm: "T-Shirt",
        title: "not-today",
        about: `A bright red T-shirt with a bold "Not Today" message is the perfect choice for those who like to stand out and express their mood through style. Its minimalistic design and laconic text add a touch of humor and confidence to the image. Material: natural cotton, soft and pleasant to the body, providing comfort. With this T-shirt you can not only look stylish, but also express your mood brightly and confidently!`,
        sizeOneSale: "S 36",
        sizeTwoSale: "M 38",
        sizeFreeSale: "L 40",
        sizeFourSale: "XL 42",
        price: "7.00",
        image: "https://images.unsplash.com/photo-1551799517-eb8f03cb5e6a?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
        id: 11,
        name: "Creative T-Shirt",
        searchTerm: "T-Shirt",
        title: "creative-t-shirt",
        about: "A minimalist black tee is a wardrobe staple that combines simplicity and style. Its laconic design without unnecessary details makes it easy to combine with other elements of clothing, creating both casual and more sophisticated looks. The black color adds versatility, while the quality fabric ensures all-day comfort. Material: Cotton is soft and comfortable to the touch for comfort and durability. This black T-shirt is a great choice for those who value simplicity, but are not willing to sacrifice style and quality.",
        sizeOneSale: "S 36",
        sizeTwoSale: "M 38",
        sizeFreeSale: "L 40",
        sizeFourSale: "XL 42",
        price: "5.00",
        image: "https://images.unsplash.com/photo-1583744946564-b52ac1c389c8?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
    {
        id: 12,
        name: "Fearss kill dreams",
        searchTerm: "T-shirt",
        title: "fearss-kill-dreams",
        about: `The black "Fears Kill Dreams" T-shirt is a powerful addition to your wardrobe that combines style with a deep message. This T-shirt is not only comfortable, but also inspires you to take courageous actions and follow your goals. The sleek design and expressive phrase make it an ideal choice for those who value self-expression and positive thinking. With this T-shirt you will not only feel comfortable, but also inspire others to take bold steps!`,
        sizeOneSale: "S 36",
        sizeTwoSale: "M 38",
        sizeFreeSale: "L 40",
        sizeFourSale: "XL 42",
        price: "8.00",
        image: "https://images.unsplash.com/photo-1612428057119-7232b9195719?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
    },
]